name: Swift

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    name: Run tests
    runs-on: macos-latest
    strategy:
      matrix:
        xcode_version: ["12.4"]
      fail-fast: false

    steps:
    - uses: actions/checkout@v2
    
    - name: Show environment
      run: |
        swift --version
        xcodebuild -version
        
    - name: Package Tests
      run: |
        swift build -v
        swift test -v
        
